### ISSUE TITLE
Separate episode files for V9

### ISSUE THREAD

**Issue by ProfessionalismIsMyMiddleName** [mercenarylongest/mercenarylongest.github.io#2]
Would it be possible to replace the V9 rip by separate episode files like all other seasons?
Pretty please?

**Comment by blakeplusplus** [comment]
Since the rip already has the chapters included, you can use [Lossless Cut](https://github.com/mifi/lossless-cut) to easily and automatically separate the files out into episodes with all the tracks intact. I just tested it myself. Give it a shot and let me know if it works for you.
